import type { AuditEvent } from "../api/client";

export interface ReportConfig {
  timeRange: "7d" | "30d" | "90d";
  framework: "SOC2" | "HIPAA" | "Custom";
  events: AuditEvent[];
  stats: {
    total: number;
    blocked: number;
    blockedPct: number;
    activeGuards: string[];
    policyVersion: string;
    topViolations: Array<{ guard: string; count: number }>;
  };
}

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateReportHTML(config: ReportConfig): string {
  const { framework, timeRange, stats } = config;

  const violationRows = stats.topViolations
    .map((v) => `<tr><td>${escHtml(v.guard)}</td><td>${v.count}</td></tr>`)
    .join("");
  const guardRows = stats.activeGuards
    .map((g) => `<tr><td>${escHtml(g)}</td><td>Active</td></tr>`)
    .join("");

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>ClawdStrike Compliance Report</title>
<style>body{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;color:#1a1a1a;line-height:1.6}
h1{font-size:24px;border-bottom:2px solid #d6b15a;padding-bottom:8px}h2{font-size:18px;margin-top:32px;color:#333}
table{width:100%;border-collapse:collapse;margin:16px 0}th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #e5e5e5}
th{background:#f5f5f5;font-size:13px;text-transform:uppercase;letter-spacing:0.05em;color:#666}
.stat{display:inline-block;margin:0 24px 16px 0}.stat-value{font-size:28px;font-weight:700}.stat-label{font-size:12px;color:#888;text-transform:uppercase}
footer{margin-top:48px;padding-top:16px;border-top:1px solid #e5e5e5;font-size:12px;color:#999}</style></head>
<body><h1>ClawdStrike Compliance Report — ${framework}</h1>
<p>Time range: ${timeRange} · Generated: ${new Date().toLocaleDateString()}</p>
<h2>Executive Summary</h2>
<div class="stat"><div class="stat-value">${stats.total}</div><div class="stat-label">Total Actions</div></div>
<div class="stat"><div class="stat-value">${stats.blockedPct.toFixed(1)}%</div><div class="stat-label">Blocked</div></div>
<div class="stat"><div class="stat-value">${stats.activeGuards.length}</div><div class="stat-label">Active Guards</div></div>
<h2>Top Violations</h2>
<table><thead><tr><th>Guard</th><th>Count</th></tr></thead>
<tbody>${violationRows}</tbody></table>
<h2>Guard Activity</h2>
<table><thead><tr><th>Guard</th><th>Status</th></tr></thead>
<tbody>${guardRows}</tbody></table>
<p>Policy version: ${stats.policyVersion}</p>
<footer>Generated by ClawdStrike Dashboard · ${new Date().toISOString()}</footer></body></html>`;
}

export function downloadReportHTML(html: string, filename: string): void {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

export function printReport(html: string): void {
  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
    w.print();
  }
}
